### ISSUE TITLE
need multi-filter,it seems that wfst don't support。

### ISSUE THREAD

**Issue by bation** [Flexberry/Leaflet-WFST#83] opened 2019-07-23 10:31 UTC
I know someone has an issue about this ,but until now wfst still do not support multi-filter,I don't understand why,it's very usefull .if we don't support ,I have to get jsons and filter myself with for & if statement,that's ugly,beleave me.

**Comment by kuzkok** [comment] 2019-09-04 06:42
Duplicate of #48 
Multi-filter exists in develop branch and beta releases.

**Closed as completed by kuzkok** 2019-09-04 06:42 UTC
Labels: duplicate

**Comment by kuzkok** [comment] 2019-09-04 06:45
multi filter exists in develop branch and beta releases
